# Generated by Django 4.2 on 2023-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
            ],
        ),
    ]
