# Generated by Django 4.2 on 2023-04-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BemVindo',
            new_name='Paciente',
        ),
    ]
